### ISSUE TITLE
Planned support for other file formats?

### ISSUE THREAD

**Issue by hrxn** [Kagami/wybm#9]
First of all: Thank you, very interesting project!

It appears to be just what I was looking for, so thank you for making this.

According to the description (and title), it is explicitly made for the Webm container, but why does it require MKVToolNix (mkvinfo) then?

Also, how about supporting MP4? Shouldn't ffmpeg be able to handle this?

Oh, and by the way: The Demo video (demo.webm) is not working?

**Comment by Kagami** [comment]
Hi, thank you for your interest.

>why does it require MKVToolNix

mkvtoolnix supports webm (since webm is just a subset of matroska) and wybm needs mkvinfo in order to parse information about frames in video (keyframe flag, size, position, etc). (In fact it's possible to parse than info with ffprobe or even with minimal EBML parser.)

I'm not planning to implement MP4 support because this tool was created specially for generating webms in the end. But you're right, ffmpeg does support "-c copy" for MP4 container, you could also try e.g. avidemux GUI program.

>The Demo video (demo.webm) is not working?

In what player (browser) are you trying to open it? Works for me in Firefox.

**Comment by hrxn** [comment]
> In what player (browser) are you trying to open it? Works for me in Firefox.

Chrome 55.0.2883.75 (Official Build) m (64-bit)
Windows 10 x64

> I'm not planning to implement MP4 support [..]

Too bad, but that's your prerogative, of course.

> [..]  you could also try e.g. avidemux GUI program.

You're right.. I used this actually a (long) while ago, and thought it was specifically for .AVI, but it also seems to support MP4, true.

**Comment by Kagami** [comment]
>Chrome 55.0.2883.75

Hm, you're right, seems to be CSP issue, either on GitHub or Chrome side. WebM is completely fine, you can save it and open from disk.
